### ISSUE TITLE
Deine Aufgabe

### ISSUE THREAD

**Issue by ariogato** [ariogato/sr_steppermotors#1]
Du darfst den Code in der loop-funktion so erweitern, dass auch Parameter (Entfernung bzw. Grad bei Drehungen) über UART an den Arduino weitergegeben werden können. 
Diese erhaltenen Informationen muss der Arduino dann natürlich auch entsprechend verarbeiten können.

**Comment by DankBen** [comment]
ok du arsch

**Comment by ariogato** [comment]
und wie weit sind wir?

**Comment by DankBen** [comment]
wir sind am essen

**Comment by ariogato** [comment]
lecker lecker
